# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the dev branch
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
          
jobs:

  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: tasks_base
          POSTGRES_PORT: 5432
        ports:
          - 5432/tcp
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Run
        env:
          # These are the expected envs in my code
          DB_HOST: localhost
          DB_USER: test
          DB_PASSWORD: test
          DB_NAME: tasks_base
          DB_PORT: 5432
          DB_DIALECT: postgres
          PORT: 8080
        run: make run
